language: node_js
node_js: '8.11.2'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
install:
  - bash ./scripts/install-yarn-dependencies.sh
stages:
  - name: test
    if: (type IN (pull_request)) OR (type IN (push) AND branch = master)
  - name: deploy api
    if: (type IN (push) AND branch = release)
  - name: deploy mobile
    if: (type IN (push) AND branch = release)
jobs:
  include:
    - stage: test
      script:
        - bash ./scripts/global-npm-script.sh lint
    - script:
        - travis_wait bash ./scripts/global-npm-script.sh test "travis" && bash ./scripts/global-npm-script.sh codecov
    - stage: deploy api
      script: skip
      before_deploy: npm install -g now
      deploy:
        - provider: script
          script: cd api && now --public --token $NOW_TOKEN && now alias --token $NOW_TOKEN
          skip_cleanup: true
          on:
            tags: true
    - stage: deploy mobile
      script: skip
      deploy:
        - provider: script
          script: bash ./scripts/create-mobile-release.sh
          skip_cleanup: true
          on:
            tags: true
